"""Add is_active to Product model for soft delete

Revision ID: c408105f3fb8
Revises: ed8e59802172
Create Date: 2025-08-11 08:55:20.201176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c408105f3fb8'
down_revision = 'ed8e59802172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_shop_per_user', ['name', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_constraint('unique_shop_per_user', type_='unique')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
